### ISSUE TITLE
Vectorized polynomial evaluation

### ISSUE THREAD

**Issue by michaelgordy** [RobinHankin/mvp#20]
I have an application that is very sensitive to speed.  I'm finding mvp significantly faster than mpoly for manipulation of bivariate polynomials, but much slower for evaluation. In my setting, I have vectors of values for x and y and need to calculate ans[j]=p(x[j],y[j]). mpoly gives the option to vectorize when coercing to a function, but it appears that mvp takes only scalar inputs so I'm forced to loop.  Any possibility of adding this feature in the next release?

**Comment by RobinHankin** [comment]
hello, happy to help here.  I hadn't realised that mpoly was vectorized in this way (nor that it might be important).   I'm not 100% sure what `ans[j]=p(x[j],y[j])` means; if you post a simple hello-world example I'll do my best!

**Comment by RobinHankin** [comment]
see also issue #21

**Comment by michaelgordy** [comment]
Thank you for writing, Robin.  I've benefited greatly over the years from your packages (especially gsl and partitions), so it's a pleasure.
It does appear that my issue coincides with #21.  I wonder if the issue is that "subs" was perhaps designed more with symbolic substitution in mind than with numeric evaluation?  

On my server at the office, I have a working example of vectorized evaluation in mpoly.  I'll send it to you later today from my frb.gov address.
Best wishes,Michael

    On Monday, July 29, 2019, 10:58:07 PM EDT, Robin Hankin <notifications@github.com> wrote:  
 
 
see also issue #21

**Comment by RobinHankin** [comment]
Hello Michael, thank you for your kind words.  I think you're right about `subs()`;  when I was developing mvp I got a little bit obsessed with the symbolic aspects of it, at the expense of speed (which was the original motivation for the package).

One other thought that occurred to me was that you could use the spray package, which implements sparse arrays in R, again using the STL.  This has some functionality for multivariate polynomials but lacks the symbolic aspects of mpoly and mvp.  I suspect that spray might be even faster than mvp for bivariate polynomials: in spray idiom, the index matrix would not be sparse, so there would be no advantage in using mvp.  But I'd be very interested to know timings.

Unless I've missed a trick (which is not inconceivable!), spray has the same unvectorizability as mvp.

I think it is possible to implement vectorised substitution on the C side in mvp but it's not entirely trivial; I will need one or maybe two new C++ classes.  I'll start a new feature branch for this, but finishing it might take some time. 

Best wishes

Robin

**Comment by michaelgordy** [comment]
Writing from office.  Here is a simple example of the “vectorized” version of polynomial evaluation in mpoly.  Somewhat confusingly, one sets “vector=FALSE” to get the desired effect.  When vector=TRUE, the user must input the argument values as a single vector, which is useful only when one has a single vector of arguments to evaluate.

Thanks,
Michael

**Comment by RobinHankin** [comment]
hello again Michael.

I'm not sure I'm looking in the right place, but I don't see the vectorized mpoly example.  Could you advise?

**Comment by michaelgordy** [comment]
Thank you for the suggestions, Robin.  I'll look at spray.  In the meantime, I've realized that my bivariate polynomial decomposes into a sum of a small number of products of univariate polynomials.  This seems to be the fast way to evaluate.  Feel free to close my `issue` or merge with the other one.

I will try to embed my vectorized mpoly example below.  The final bit (with j set to 50) is simply to confirm that the mvp result matches the mpoly result.

`library(mvp)
library(mpoly)

n <- 100
x1 <- runif(n, min = -1, max = 1)
x2 <- runif(n, min = -1, max = 1)

p_mvp <- rmvp(20, symbols=2)
p_mpoly <- as.mpoly.mvp(p_mvp)
f_mpoly <- as.function(p_mpoly, varorder=c("a","b"),
                vector = FALSE, silent = TRUE)
ans_mpoly <- f_mpoly(x1, x2)

j <- 50
ans_mvp <- subs(p_mvp,a=x1[j], b=x2[j])
print(all.equal(ans_mpoly[j], ans_mvp))`

**Comment by RobinHankin** [comment]
Michael, thanks for this.  Please see below a slightly modified version of your R idiom which includes a demonstration from the spray package, which (unlike the current version of mvp) takes vector arguments for substitution:
```
library("mvp")
library("mpoly")
library("spray")

n <- 100
x1 <- runif(n, min = -1, max = 1)
x2 <- runif(n, min = -1, max = 1)

p_mvp <- rmvp(20, symbols=2)
p_mpoly <- as.mpoly.mvp(p_mvp)
p_spray <- mvp_to_spray(p_mvp)

f_mpoly <- as.function(p_mpoly, varorder=c("a","b"),vector = FALSE, silent = TRUE)
f_spray <- as.function(p_spray)

ans_mpoly <- f_mpoly(x1, x2)
ans_spray <- f_spray(cbind(x1, x2))

j <- 50
ans_mvp <- mvp::subs(p_mvp,a=x1[j], b=x2[j])
print(all.equal(ans_mpoly[j], ans_mvp))
print(all.equal(ans_mpoly, ans_spray))
```
(is there an easier way to pass rapid turnaround code snippets like this around?).  Anyway, then we have

```
> source("~/fff.R")
[1] TRUE
[1] TRUE
> 
```

**Comment by michaelgordy** [comment]
I gave it a try and timed the results using `rbenchmark` and larger `n=2500`.
```
xx <- cbind(x1, x2)
tmgs <-
  benchmark("mpoly" = f_mpoly(x1, x2),
            "spray" = f_spray(xx),
            replications=15)
```

I find `mpoly` is about 20-25% faster.  So, while `mpoly` is slow for many symbolic operations, it does seem the best option right now for numeric evaluation.

**Comment by RobinHankin** [comment]
Thanks for this Michael, my timings agree with yours.  For this case I would have guessed that spray would have been a little bit faster than spray, but these results show that R's list processing is faster than I'd thought.  We should share this work with David Kahle, do you have any objection?

Even though it probably won't be much faster in this case, I'm working on vectorised subsitution in the mvp package (on the `feature` branch) but there is some bug somewhere which I can't find.
Best wishes,  Robin

**Comment by RobinHankin** [comment]
Michael, I've just merged some work on vectorised substitution to the master branch and there is now a function ```subvec()``` that should work as expected for you.  Let me know you you get on.  Best wishes, Robin

**Comment by michaelgordy** [comment]
Thank you, Robin.  I was traveling so away from my desktop.  I just tested it against mpoly and spray by tweaking the previous script.   For `n=10000`, mvp has a slight advantage over mpoly (about 3% faster) and a 20% advantage over spray.  I haven't tried higher order polynomials, but really this is very nice.

Is the dependence on mpoly avoidable? I ask because my colleague complains that mpoly has some conflict with dplyr and (apparently) with magrittr, and in general seems to trigger hard-to-diagnose bugs in our code. I don't know the details and don't know if my colleague is to blame, but mention it as something to consider.  In my view, mvp is now strictly better than mpoly (though I can't claim to have tested all use cases).

Please mark the issue as closed!

**Comment by RobinHankin** [comment]
hello again Michael, thanks for this, I'll close this issue and open another one on `mpoly` dependence.

Best wishes

Robin

**Comment by RobinHankin** [comment]
the `mpoly` dependence is issue #27
