### ISSUE TITLE
aderiv() does not behave as expected when R passing variables to arguments for which variables to differentiate WRT

### ISSUE THREAD

**Issue by briankleiboeker** [RobinHankin/mvp#63]
Hello,
I'm having some trouble trying to use mvp::aderiv dynamically in a function I'm writing. The issue is best illustrated below:

```
> x <- paste0(c("C","H","O","N"))[1]
> y <- paste0(c("C","H","O","N"))[1]
> x
[1] "C"
> y
[1] "C"
> b<-as.mvp("24.1878 C H + 336.0738 C N + 383.8776 C O - 15037.01 C m + 144 C^2 + 28.2253 H N + 32.24012 H O - 1262.89 H m + 1.015711 H^2 + 447.9555 N O - 17547.03 N m + 196.0861 N^2 - 20042.96 O m + 255.8368 O^2 + 392555.1
m^2")

> mvp::aderiv(expr = b,x = 1,y = 1)
mvp object algebraically equal to 0
> mvp::aderiv(expr = b,C = 1,C = 1)
mvp object algebraically equal to 288
```

I've tried every trick I can find with `!!` before x and y, using `assign()` or `eval()` or `{}` or `{{}}` to wrap x and y, all to no avail, though some of these do instead yield the error message: Error: unexpected '=' in "mvp::aderiv(expr = b,!!x ="

Thanks for your work on this great package!

**Comment by RobinHankin** [comment]
hello, thank you for your kind words!

Happy to help.  But I'm not sure I understand your question.   I guess you
are wanting to create a function that takes a letter (one of "C", "H" "O"
or "N") and return the derivative of mvp object 'b' with respect to that
argument? If so:

> f <- function(thing1,thing2){deriv(b,c(thing1,thing2))}
> f("C","N")
mvp object algebraically equal to
336.0738
> f("N","C")
mvp object algebraically equal to
336.0738
> t1 <- "N"
> f(t1,"C")
mvp object algebraically equal to
336.0738

but I think I've missed the thrust of your question here. Let me know


best wishes

Robin




--
Robin K. S. Hankin
Associate Professor, computational statistics

**Comment by briankleiboeker** [comment]
I think you do understand what I'm trying to accomplish: I have a function b and I want to iterate through all of the variables to take their partial derivatives and create a Hessian matrix. 

> b<-as.mvp("24.1878 C H + 336.0738 C N + 383.8776 C O - 15037.01 C m + 144 C^2 + 28.2253 H N + 32.24012 H O - 1262.89 H m + 1.015711 H^2 + 447.9555 N O - 17547.03 N m + 196.0861 N^2 - 20042.96 O m + 255.8368 O^2 + 392555.1
m^2")
>
> variable.list <- paste0(c("C","H","O","N"))
>
> for(i in 1:length(variable.list){
>      for(j in 1:length(variable.list){
>           hess[i,j] <- mvp::aderiv(b, variable.list[i] = 1, variable.list[j] = 1)
>      }
> }
> 

But as I've been testing this outside of the loop, I'd say that my confusion really boils down to why I can't pass any R variables into the variable arguments of `aderiv()`. I think a minimum example of this issue looks like:


> x <- "C"
> y <- "C"
> x
[1] "C"
> y
[1] "C"

Using the variables x and y does not work, yielding either zero or the Error: unexpected '=' in "mvp::aderiv(expr = b,!!x =" when  I try to change how the variables are evaluated (I have also tried `unquote()` to no avail)
> mvp::aderiv(expr = b,x = 1,y = 1)
mvp object algebraically equal to 0

Yet passing in C this way works just fine
> mvp::aderiv(expr = b,C = 1,C = 1)
mvp object algebraically equal to 288

Anyways, the solution in your response seems to work brilliantly! Is it safe to assume that passing the arguments into `deriv()` the way you did (with `c(a,b,...)`) will take the first order partial derivates equivalently to `aderiv()`? Thanks so much for your help!

**Comment by RobinHankin** [comment]
OK, good to know you got a working solution there.  For the record, here is my idiom for the Hessian:

```
b <- as.mvp("24.1878 C H + 336.0738 C N + 383.8776 C O - 15037.01 C m + 
144 C^2 + 28.2253 H N + 32.24012 H O - 1262.89 H m + 1.015711 H^2 + 447.9555 N O
- 17547.03 N m + 196.0861 N^2 - 20042.96 O m + 255.8368 O^2 + 392555.1 m^2")

variable.list <- paste0(c("C","H","O","N"))
hess <- matrix(NA,4,4)

for(i in 1:length(variable.list)){
  for(j in 1:length(variable.list)){
    hess[i,j] <- lose(mvp::deriv(b, c(variable.list[i], variable.list[j])))
  }
}

rownames(hess) <- variable.list
colnames(hess) <- variable.list
print(eigen(hess,T,T))
```

[sadly(?) not positive-definite!] I will add a similar example to the docs somewhere when I get a minute (actually the fact that I had to use `lose()` rather than the more standard `drop()` [which is used, e.g. in `clifford` and `weyl`] tripped me up, and this is reminds me that issue #48 remains unresolved). But this still leaves your original question of how to pass named arguments to `aderiv()`.  Here is one not particularly elegant solution:

```
> f <- function(v){do.call("aderiv",list(b,setNames(rep(1,length(v)),v)))}
> f(c("C","N"))
mvp object algebraically equal to
336.0738
> aderiv(b,C=1,N=1)
mvp object algebraically equal to
336.0738
> 
```

**Comment by RobinHankin** [comment]
closing now that #48 is fixed.
